apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
        - name: exchange
          image: youcancallmegus/exchange:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: exchange
spec:
  selector:
    app: exchange
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP