apiVersion: v1
kind: Secret
metadata:
  name: exchange-secret
type: Opaque
stringData:
  EXCHANGE_API_KEY: exchange_api_key

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: exchange-config
data:
  APP_ENV: production
  APP_PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
        - name: exchange
          image: youcancallmegus/exchange:latest
          ports:
            - containerPort: 8080
          env:
            - name: EXCHANGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: exchange-secret
                  key: EXCHANGE_API_KEY
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: exchange-config
                  key: APP_ENV
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: exchange-config
                  key: APP_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: exchange
spec:
  selector:
    app: exchange
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP